#include "arduino_secrets.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/dcdff633-33d0-4368-b33a-e938f2804088 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool buzzerControl;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const char* ssid = "ESP32_Direct";
const char* password = "12345678";

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  #include "WiFi.h"

  // This code is from AI
  // Start Wi-Fi in AP (Wi-Fi Direct) mode
  // WiFi.mode(WIFI_AP);
  // bool result = WiFi.softAP(ssid, password);

  // if(result){
  //   Serial.println("WiFi Direct Started Successfully!");
  //   Serial.print("IP Address: ");
  //   Serial.println(WiFi.softAPIP());
  // } else {
  //   Serial.println("WiFi Direct Failed!");
  // }

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

// This code only applies to button logic
void loop() {
  ArduinoCloud.update();
  // Your code here
  Serial.print(millis());
  Serial.print(" ");
  Serial.println(current_state);
  current_state = fsm(BUTTON_PIN, current_state); // This is where I need to modify for button
  if ((current_state != past_state) && (current_state == UP || current_state == DOWN)){
    digitalWrite(BUZZER_PIN, current_state);
    Serial.println("Inside digital write");
    Serial.print(millis());
    Serial.print(" ");
    Serial.println(current_state);
    past_state = current_state;
  }
}


/*
  Since BuzzerControl is READ_WRITE variable, onBuzzerControlChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBuzzerControlChange()  {
  // Add your code here to act upon BuzzerControl change
  digitalWrite(BUZZER_PIN, HIGH); // Turn on buzzer
  delay(500); // Pause for a second 
  digitalWrite(BUZZER_PIN, LOW); // Turn off buzzer
  delay(250); // Pause for a second 
  digitalWrite(BUZZER_PIN, HIGH); // Turn ON buzzer
  delay(500); // Pause for a second 
  digitalWrite(BUZZER_PIN, LOW); // Turn off buzzer
}