// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define BUTTON_PIN 0
#define BUZZER_PIN 6

typedef enum {UP=0, DOWN, PRESS, RELEASE} ButtonState;

ButtonState current_state = UP;
ButtonState past_state = UP;

volatile bool buttonChanged = false;

ButtonState fsm(int i_pin, ButtonState state_current);

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBuzzerControlChange();

bool buzzerControl;

void initProperties(){

  ArduinoCloud.addProperty(buzzerControl, READWRITE, ON_CHANGE, onBuzzerControlChange);
  pinMode(BUZZER_PIN, OUTPUT);
  pinMode(BUTTON_PIN, INPUT);
  digitalWrite(BUZZER_PIN, LOW);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

ButtonState fsm(int i_pin, ButtonState state_current){
  //Look for button press
  const static unsigned long debounce_t = 50;
  static unsigned long last_bounce = millis();
  bool reading = digitalRead(i_pin);
  static bool last_reading = LOW;
  // Guard rails on button press
  if (reading!=last_reading) {
    last_bounce = millis();
  }

  if (millis() - last_bounce >= debounce_t){
    switch(state_current){
      case UP:
        if (reading == DOWN) {state_current = PRESS;}
        break;
      case DOWN:
        if (reading == UP) {state_current = RELEASE;}
        break;
      case PRESS:
        state_current = DOWN;
        break;
      case RELEASE:
        state_current = UP;
        break;
    } 
  }
  last_reading = reading;
  return state_current;
}
